### ISSUE TITLE
Support for Dolibarr 6.0

### ISSUE THREAD

**Issue by xelan** [Befox/cdav#12]
Hi Jean-Pierre!

Thank you for developing this interesting module for Dolibarr. Do you have any plans to adapt it for the recently published [Dolibarr 6.0](https://www.dolibarr.org/87-news/announces/265-dolibarr-erp-crm-6-0-has-been-released)?

Best regards
xelan

**Comment by jpfox** [comment]
It works with Dolibarr 6.x

**Comment by xelan** [comment]
Great, thank you very much for the feedback @jpfox :+1:
