### ISSUE TITLE
mcrypt_ecb() DEPRECATED in PHP 5.5.0, and REMOVED in PHP 7.0.0.

### ISSUE THREAD

**Issue by bjoern86** [Befox/cdav#14]
Fatal error: Uncaught Error: Call to undefined function mcrypt_ecb() in /htdocs/cdav/cdavurls.php:134 Stack trace: #0 {main} thrown in /htdocs/cdav/cdavurls.php on line 134

php.net (http://php.net/manual/de/function.mcrypt-ecb.php) says:

This function was DEPRECATED in PHP 5.5.0, and REMOVED in PHP 7.0.0.
Alternatives to this function include:
mcrypt_decrypt()
mcrypt_encrypt()

**Comment by jpfox** [comment]
Perfect @bjoern86
