### ISSUE TITLE
LDAP Compatible?

### ISSUE THREAD

**Issue by Keelan** [Befox/cdav#2]
I authenticate with LDAP on dolibarr.

I have installed this module but i can never successfully login. If i go to http://mydomain.com/cdav enter a user and password it fails and asks for it again. I can't authenticate on any client either. Same credential log me into dolibarr no issues.

Running:
dolibarr 3.9.0
cdav 1.03
Apache
Php 5.5.31

(great module btw)

**Comment by midfox** [comment]
Hi Keelan,

Thanks for your interest for our module.
Unfortunately, this kind of authentication (LDAP) is not supported by
the module.
Maybe in the future,  but there is no roadmap at the moment.

Regards,

Befox Team

  Befox

Web : www.befox.fr <http://www.befox.fr/>
Tél : 04 75 06 56 02
Clé <https://fr.wikipedia.org/wiki/GNU_Privacy_Guard> : 0xD21F599D <http://www.befox.fr/gpg/0xD21F599D-contact@befox.fr>

**Comment by Keelan** [comment]
@midfox 

That is unfortunate, thank you for your response though.

**Comment by jpfox** [comment]
Last version (master branch) permits LDAP authentication
