### ISSUE TITLE
URL CalDAV - Use of undefined constant CDAV_URI_KEY - assumed 'CDAV_URI_KEY'

### ISSUE THREAD

**Issue by matll42** [Befox/cdav#22]
Hi,

When I open my CalDAV URL (given by URL CalDAV page in agenda), it returns me an error in XML:

```xml
<d:error>
  <s:sabredav-version>3.0.0</s:sabredav-version>
  <s:exception>ErrorException</s:exception>
  <s:message>Use of undefined constant CDAV_URI_KEY - assumed 'CDAV_URI_KEY'</s:message>
</d:error>
```

I saw that CDAV_URI_KEY is define with conf->global->CDAV_URI_KEY by I can't find such configuration neither in module neither in dolibarr configuration. Where does I need to be configured?

So I can't sync my dolibarr agenda with my calendar client due to this error.

Mathieu
Dolibarr 6.0.5
PHP7.0.3
CDav1.02

**Comment by jpfox** [comment]
please test with last version of cdav ;-)

**Comment by jpfox** [comment]
Constant management is now corrected since this commit : https://github.com/Befox/cdav/commit/4863c4999d544403fd820ba0b1ee5abc6ab9b3ea
Download last version of cdav module
