### ISSUE TITLE
Sync project Tasks

### ISSUE THREAD

**Issue by fbagnol** [Befox/cdav#25]
Hi

Is it possible to sync project tasks ?

Regards.

**Comment by jpfox** [comment]
Hi,

We have not tested these kind of tasks. So we don't know if they are synced...

**Comment by fbagnol** [comment]
these kind of tasks are not in the same table as calendar events...

**Comment by jpfox** [comment]
Project tasks sync will be developed soon.

Each project task will appear in Calendar (to easily adjust dates) and in Todo (to set progression status in %).

**Comment by jpfox** [comment]
Last version includes this enhancement
