### ISSUE TITLE
Disparition des events lors de l'ajout sous Calendrier / Rappels (Apple)

### ISSUE THREAD

**Issue by kopierreko** [Befox/cdav#26]
Bonjour,

Lorsque j'ajoute un évènement ou un rappel sour Calendrier / Rappels, ils s'ajoutent sur Dolibarr mais disparaissent des applications quelques secondes après... Et je ne vois aucun évènement de Dolibarr. J'ai l'impression que la communication ne se fait que dans un sens.

Avez-vous une idée du problème ?

Merci

**Comment by jpfox** [comment]
Bonjour,

Il se peut qu'un des éléments du calendrier contiennent des caractères spécifiques, il faudrait activer le mode débogage  sur votre serveur et analyser les échanges.

Dans https://github.com/Befox/cdav/blob/master/server.php ligne 32/33 en précisant un nom de fichier auquel vous avez accès.

    // debug
    $debug_file = fopen('/tmp/cdav_'.date('Ymd').'.log','a');
    // $debug_file = false;`
