### ISSUE TITLE
Liens non fonctionnels après installation du module

### ISSUE THREAD

**Issue by dauge** [Befox/cdav#27]
Bonjour,

Sur une instance Dolibarr 5.0.7 / Debian stretch, php7.0.33-0+deb9u1, les liens URL CardDAV, URL CalDAV et URL ICS affichent des pages blanches.

Le module apache dav n'est pas actif, le paquet php-sabre-dav-2.1 est bien installé.

J'ai les erreurs apache suivantes au chargement de la page:
`[Fri Dec 21 17:04:17.934811 2018] [:error] [pid 7847] [client 78.209.46.78:54746] PHP Warning:  require(../../main.inc.php): failed to open stream: No such file or directory in /usr/local/share/dolibarr/htdocs/cdav/server.php on line 88
[Fri Dec 21 17:04:17.934849 2018] [:error] [pid 7847] [client 78.209.46.78:54746] PHP Fatal error:  require(): Failed opening required '../../main.inc.php' (include_path='.:/usr/share/php') in /usr/local/share/dolibarr/htdocs/cdav/server.php on line 88
`

**Comment by jpfox** [comment]
Bonjour,
il ne faut pas installé le paquet php-sabre-dav, sabredav est fourni avec le module cdav.
Pour l'erreur, c'est étrange. Il ne trouve pas le fichier main.inc.php
Ce fichier est il bien présent sur votre serveur : /usr/local/share/dolibarr/htdocs/main.inc.php ?

**Comment by dauge** [comment]
Réglé en ajoutant un lien vers le fichier main.inc.php depuis le répertoire /usr/local/share/dolibarr/htdocs/
Merci pour l'aide !
