### ISSUE TITLE
Only getting 404.

### ISSUE THREAD

**Issue by steinymity** [Befox/cdav#28]
I am using Dolibarr 8.0.3 and installed and activated cdav. 

I can successfully access `https://server.example.com/dolibarr/htdocs/cdav/server.php` after entering my credentials and get a page with links to `adddressbooks`, `calendars`, `principals`, `public`, and, for administrators, `documents`.

However, all links just give me the standard dolibarr 404 page. What am I doing wrong here? Do I need to setup a rewrite rule to enable resoling links like `https://server.example.com/dolibarr/htdocs/cdav/server.php/addressbook`?
Since I can successfully authenticate, I guess that the rewrite issues described in the readme do not apply here.

My environment:
* Debian Stretch
* Nginx as reverse proxy for HTTPS
* Nginx as serving proxy using php-fpm for php
* Dolibarr 8.0.3 installed from the Debian package.

Thanks for your support!

**Comment by jpfox** [comment]
it's strange, generally, when authentication is good, accessing other pages works.

I do not use nginx (only apache). It seems that part after server.php is not pass to php as query-string. Have a look her maybe : https://serverfault.com/questions/685525/nginx-php-fpm-query-parameters-wont-be-passed-to-php

**Comment by steinymity** [comment]
Thanks a lot for your fast reply! 
Indeed you're right — my nginx configuration only allowed locations ending in `php` to be processed by php-fpm.
Now, I use [the example config on nginx's homepage](https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/) which includes explanation about PATH_INFO and works like a charm.
