### ISSUE TITLE
Https?

### ISSUE THREAD

**Issue by ronald1090** [Befox/cdav#3]
Is it possible to use this caldav without https? 
i always get a 401 Error with davdroid. 
Thank you for you help...

**Comment by jpfox** [comment]
there's no reason to not work.
you can check by using cdav url through a simple web browser. navigate into menu to a caldav cart and check if url stay in http.

Maybe you have configure Dolibarr or your web hosting to force https ?

**Comment by ronald1090** [comment]
Thank you for your answer. Everything worked fine after a new install of Dolibarr 3.9.2.
