### ISSUE TITLE
TbSync is able to do autodetect

### ISSUE THREAD

**Issue by jobisoft** [Befox/cdav#30]
In your Readme you State, TbSync needs the full url. I actually designed it to autodetect all resources. Are you sure it is not working with your sever?

**Comment by jpfox** [comment]
@midfox is checking this point...

**Comment by jobisoft** [comment]
Otherwise I would be happy to get a test account so I can look into this and fix it on my side!

**Comment by midfox** [comment]
Test succesfully passed with domain url only (ie : https://server.example.com)
Documentation will be update asap...
Thks @jobisoft for your remark!

**Comment by cfoellmann** [comment]
CLOSE this
