### ISSUE TITLE
Sync with DAVDroid not working

### ISSUE THREAD

**Issue by esprit-libre** [Befox/cdav#4]
Hello,
can't sync my calendar with DAVDroid whereas it works with Thunderbird.
DAVDroid version : 1.2
Dolibarr : 3.9.2
I try to use short URL (http://server.example.com/dolibarr/htdocs/cdav) and long one (http://server.example.com/dolibarr/htdocs/cdav/server.php/calendars/<connected-user-login>/<calendar-user-id>-cal-<calendar-user-login>) without success. Message is always "Aucun service CalDAV ou CardDAV trouvé." (= no service found).
Any idea ?

**Comment by jpfox** [comment]
It has been tested and work with DAVDroid.

A calendar must contain at least one "manual" event (not automatic event like "invoice creation" or what else). Is user you connect with have at least an event in his/her calendar ? Is it same user than you use with thunderbird ?

**Comment by esprit-libre** [comment]
My user is SuperAdmin user and I used the same for both Thunderbird and DAVdroid.
Yes I tried with manual events and it also contains automatic events. I already noticed that Thunderbird deactivate calendar if no events are present.
I tried yesterday with DAVdroid : no success. Today : DAV services are recognized and everything is working.
I close the case. Thanks for your attention.
