### ISSUE TITLE
Access to ECM Documents (index_auto) available via WebDAV

### ISSUE THREAD

**Issue by carlos22** [Befox/cdav#5]
Are there any plans to do that? The current file access is not very useful in my opinion. Otherwise: Great addon :heart:

**Comment by jpfox** [comment]
WebDAV access to all documents directory is active but only for admin users. It could be permitted following permission rules if necessary...

What is "ECM" documents, I don't understand.

**Comment by jpfox** [comment]
My last question is not very clear : what do you mean when writing "ECM Documents" ? all documents or just manual files tree from ECM module ?

**Comment by carlos22** [comment]
I mean all documents. Maybe I don't got how the file access works. But in my case the structure is very different from the "all documents" or generated index (second Tab in Documentsview). The folders are all installed modules. I can access the manual files tree view the "ecm" folder. But how can i get to any invoice for example?

**Comment by jpfox** [comment]
Dolibarr is a french project and sometimes there are some relics :-)

cdav webdav module does not uses ECM terms, it only give access to physical document directory on server disk, so folders tree could be different.

If you have access to documents through webdav, you could find invoices in documents/facture folder (french name). Hope it helps you.

**Comment by carlos22** [comment]
Ok. Got it. Thanks.
