### ISSUE TITLE
Why put SabreDav in lib inside the module as Dolibarr already include SabreDav ?

### ISSUE THREAD

**Issue by FHenry** [Befox/cdav#52]
Why put SabreDav in lib inside the module as Dolibarr already include SabreDav ?

**Comment by cfoellmann** [comment]
I suspect that @FHenry has issues with the very outdated version included in Dolibarr

**Comment by FHenry** [comment]
Why do not make a pr in dolibarr to upgrade it

**Comment by cfoellmann** [comment]
you can try but it would only be updated in the next release of Dolibarr 
and the devs are not open to using composer like it should be used.

**Comment by cfoellmann** [comment]
Since dolibarr is going for php >= 8.0 I would send a PR for SabreDav to dolibarr if @jpfox is open for using the included version

**Comment by jpfox** [comment]
When cdav was written, in first versions, sabre/dav was not included into Dolibarr.
I discover it with your message.
Maybe in a future release, cdav will use embedded version of SabreDAV :-)

**Comment by cfoellmann** [comment]
So let me send a PR for SabreDav 4.4.0 to dolibarr core?

17.0 will be ready soon so the update might be perfect for the next development cycle.

**Comment by FHenry** [comment]
at least in version 18.0 sabredav is upgrade to 4.5.1
https://github.com/Dolibarr/dolibarr/pull/24898/files#diff-aa6b3e61abceef63b8298be436d830ed58670f126812dfb028f1094cc238de79

**Comment by FHenry** [comment]
I close the issue, as the PR https://github.com/Befox/cdav/pull/56 is open in waiting to be merged
