### ISSUE TITLE
Update 2.20 -> Your Composer dependencies require a PHP version ">= 8.0.0". 

### ISSUE THREAD

**Issue by zunami** [Befox/cdav#53]
I have a problem with the current update to 2.20
I now get this message

`Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0". `

my device has PHP 8.0 installed and works with an nginx server

**Comment by jpfox** [comment]
composer is not used to install cdav... just unzip it in your custom directory

**Comment by jpfox** [comment]
This error effectively occurs in php logs if you have not php 8 or greater. Are you sure that you run this version on your web server ?

**Comment by zunami** [comment]
hello!


I have already bring up to date to the 2.21 version .
and again the php 8 error

I have installed
php 7.4
php 8.0
php 8.1

![2022-11-28 12_22_44-Greenshot](https://user-images.githubusercontent.com/4697822/204266257-0484b46d-928f-4efd-b536-0078e32e7620.png)

**Comment by daraelmin** [comment]
Hi,

Installing PHP 8.1 is not enough. You must launch it. There can be several version of PHP on the same server (or computer), but only one can ne running at one tome. So I assume, you've just have to stop PHP 7.2.34 and Start PHP 8.1.

Cheers

**Comment by zunami** [comment]
so i have finished it now. i have version 16.0.3 with php 7.4
problem is I can not go to php 8.0 because this causes too many errors in the background.

[Dolibarr release and bug information](https://wiki.dolibarr.org/index.php/Releases)

I guess I have to wait for the dolibarr 17 until the final release with the correction to php 8.0

**Comment by jpfox** [comment]
The recent upgrade of Sabre/DAV embedded with cdav was certainly not so welcome. I think I will generate a branch dedicated to php 7.4 with the previous version of Sabre/DAV...

I will anounce it here

**Comment by zunami** [comment]
problem fixed since update to Dolibarr 17.0 and update to PHP 8.0
