### ISSUE TITLE
the plugin put all on agenda as task

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [Befox/cdav#8]
Hello,

testing the latest code with ldap support, it now connect correctly to dolibarr and sync the calendar entries but it put everything as task.

i think it should put the calendar of dolibarr (events) as clendar entries and put projects task as task.

i join screnshoot to show the actual behaviour 

![caldav-taches-agendas](https://cloud.githubusercontent.com/assets/243766/24598719/37a89bb8-184d-11e7-9baa-7d972706a7d8.png)

**Comment by jpfox** [comment]
Hello,

As mentioned in [ReadMe.md](https://github.com/Befox/cdav/blob/master/README.md) : 

> Calendar records with "Status / Percentage" set to "Not applicable" are converted to events in CalDAV (VEVENT), others are converted to tasks (VTODO).

**Comment by bilbo-the-hobbit** [comment]
hello,

ok i understand that

**Comment by bilbo-the-hobbit** [comment]
hello,

i just put a meeting request inside dolibarr with thunderbird caldav plugin into dolibarr, i work but i loose the contact that has asked for the meeting

see attached screenshot
![caldav-taches-agendas3](https://cloud.githubusercontent.com/assets/243766/24608930/f4e815de-1878-11e7-8892-66c98ea06c5f.png)
![caldav-taches-agendas4](https://cloud.githubusercontent.com/assets/243766/24608934/f7d97648-1878-11e7-952b-85fd5e89f3b4.png)

**Comment by jpfox** [comment]
Participant in event is managed specifically on each client application (Outlook, Thunderbird, Android, iOr, iCal...) and, unfortunately, we can not manage all these cases.

**Comment by bilbo-the-hobbit** [comment]
hello,

thats not true, it is send to dolibarr trough caldav protocol who is a standard and so if you have the info comming you should write it correctly in dolibarr.

Outlook doesnt do caldav and android have a nice caldav addon that work perfectly 

without that its useless if we loose all the information

**Comment by jpfox** [comment]
this discussion is now the same on issue #10
